### ISSUE TITLE
Diagram czynności logowanie

### ISSUE THREAD

**Issue by ghost** [ZespolNumerJeden/zn1#12]
Logowanie do aplikacji Webowej. Czarno - biały, ze swimlane'ami. Standard UML, standard wykonania - dok. projektowa IO grupy KanbanWSB.

**Comment by ghost** [comment]
Brak funkcjonalności w aplikacji, trzeba odwlec.

**Comment by pawelbuczynski** [comment]
Diagram weryfikujący użytkownika po mailu

**Comment by ghost** [comment]
@pawelbuczynski Nie to j.w. Zarejestrował się a teraz się loguje. Na pewno coś się po drodze sprawdza.

**Comment by ghost** [comment]
@grzegorzgogolewski Diagram czynności logowanie jest Twoją własnością i jesteś odpowiedzialny za jego prawidłowość.
