### ISSUE TITLE
Zaprojektowanie grafik

### ISSUE THREAD

**Issue by pawelbuczynski** [ZespolNumerJeden/zn1#13]

**Comment by ghost** [comment]
do strony - logo konferencji, do apki mobilnej - grafika ikony

**Comment by RadoslawBorzyszkowski** [comment]
W weekend wrzucę koncepty. Czy nawiązujemy do jakichś poprzednich materiałów?

**Comment by ghost** [comment]
@RadoslawBorzyszkowski Nie słyszałem od członków koła, żeby zależało im na ciągłości wizerunku. Niemniej myślę, że jakbyś nawiązał do numeru edycji kolejnej konferencji (trzecia), to na plus. Sczególnie w logo, które jest bardziej publiczne.

**Comment by krawan13** [comment]
przenosimy do Done ?
