### ISSUE TITLE
D Czynności Rejestracja

### ISSUE THREAD

**Issue by ghost** [ZespolNumerJeden/zn1#15]
Rejestracja do aplikacji Webowej. Diagram czarno - biały, ze swimlane'ami. Standard UML, standard wykonania - dok. projektowa IO grupy KanbanWSB.

**Comment by ghost** [comment]
Brak funkcjonalności w aplikacji, trzeba odwlec.

**Comment by pawelbuczynski** [comment]
![Diagram Czynnosci Rejestracji.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59d87a7933fd9700149419df/125516c66e82c728ace21e0d46cc9d9b249082a4cfcaa55aaa53ff872a4f67412c0ea6386497e22bb54b394d4d1f0cf31b0d0c00eef39b2eafe56e778e0902bb876e5772c73d11aebd801beb05ba75995397f4edd4189fb5646fb2c99d452c1f021288fa5d3ca29848c95af44ae14c47e9.jpg)
