### ISSUE TITLE
D czynności Rejestracja na warsztat

### ISSUE THREAD

**Issue by ghost** [ZespolNumerJeden/zn1#16]
Czarno - biały, ze swimlane'ami. Standard UML, standard wykonania - dok. projektowa IO grupy KanbanWSB.

**Comment by ghost** [comment]
Brak funkcjonalności w aplikacji, można odwlec.

**Comment by pawelbuczynski** [comment]
Diagram sprawdzenia miejsca na warsztat podczas procesu rejestracji - z uwzględnieniem maila

**Comment by ghost** [comment]
@pawelbuczynski Chodzi o kompletny diagram całej aktywności zapisu na warsztat poprzez aplikację web włączając w to na jakiej podstronce jaki przycisk ma być naciśnięty i co ma być sprawdzone.

**Comment by ghost** [comment]
@KamilGancz Diagram rejestracji na warsztat jest Twoją własnością i jesteś osobą odpowiedzialną za jego prawidłowość.
