### ISSUE TITLE
D czynności otrzymania kodu

### ISSUE THREAD

**Issue by pawelbuczynski** [ZespolNumerJeden/zn1#17]
Czarno - biały, ze swimlane'ami. Standard UML, standard wykonania - dok. projektowa IO grupy KanbanWSB.

**Comment by ghost** [comment]
Brak funkcjonalności w aplikacji, trzeba odwlec.

**Comment by ghost** [comment]
@pawelbuczynski Czyli co robię, żeby otrzymać bilet, co się dzieje aż go otrzymam.

**Comment by ghost** [comment]
@RadoslawBorzyszkowski Diagram czynności zapytania i otrzymywania kodu biletu jest Twoją własnością i odpowiadasz za jego prawidłowość.

**Comment by RadoslawBorzyszkowski** [comment]
Kto odpowiada za funkcjonalność w apce?

**Comment by ghost** [comment]
@RadoslawBorzyszkowski Arek i/lub Jacek

**Comment by RadoslawBorzyszkowski** [comment]
![czynnosc_otrzymania_kodu.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e6764d04582b0011d34950/125516c66e82c728ace21e0d46eb8e832d8c8cba8cd6b057b647e99928482e72160fac2f65c7af6aaf50740b0a0c0abe4b4a5a4dafab8e2ff3bf6a2689540decd16d5d71c43945a8b8d70da313f871d51bdaebe5c01982fa3737e682854e3b1e0c1f8afb5e35a69d43c84abb.jpg)
