### ISSUE TITLE
Plan testów

### ISSUE THREAD

**Issue by ghost** [ZespolNumerJeden/zn1#18]
Masterplan/Plan testów z AC, TS i in. 
https://docs.google.com/document/d/18s5-JYLcdZcznAAfrJn2RwA4qm0H6GTMjirItIhem88/edit?usp=sharing

**Comment by luke-tester** [comment]
@pawelbuczynski  @KamilGancz @de1takrl  Proszę o uzupełnienie oznaczonych pól :)

**Comment by krawan13** [comment]
Chodzi Ci o dokument który jest na Trello, Ogarnij-Agile-plan-testow AKTUALNY.odt ?

**Comment by luke-tester** [comment]
@krawan13 komentarz byl dla oznaczonych osob :)

**Comment by krawan13** [comment]
[Ogarnij-Agile-plan-testow_AKTUALNY.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59d87b61cab1b50012ab1e4f/125516c66e82c728ace21e0d46c7939b318c8aa3c2c8b84aa858bd842547293e3d01b03f7f92dc0994764e20232127be5d4a1f06a3a3dc78e2a436628f5558bfd6690a7d906b12a4be831fbf03bf228f1b81b6e99850d2aa6c7bb3d4d216744b470a83ed5c3caa984ec85ff048e84556a51b3764f43b.docx)

**Comment by krawan13** [comment]
ale ja nie widzę żadnych oznaczeń

**Comment by luke-tester** [comment]
@krawan13 jest w komentarzu wyzej (moim sprzed 4h) podswietlone na niebiesko.
Pawel, Kamil, Grzegorz, Ryszard powinni uzupełnić dokument zgodnie z notatkami w nim. To nie jest task dla @krawan13 @Sugar1487. Dla Was jedynie zapoznanie się z tym dokumentem.

**Comment by ghost** [comment]
@luke-tester Proszę umieścić w dokumencie punkty odnośnie wymagań i testów niefunkcjonalnych i systemowych. @ArkadioG proszę się wpisać w dokument jako odpowiedzialny za testy jednostkowe lub przydzielić programistę i wpisać. @krawan13  Dzięki za zdocxowanie tego ustrojstwa (formatu OO), proszę przeanalizować dokument pod kątem weryfikacji formalnej. Jeżeli ktoś jeszcze chce uprawnienia do edycji, proszę napisać komentarz.

**Comment by luke-tester** [comment]
@de1takrl Proszę o uzupełnienie punktu 8. - zadania przez odpowiednie osoby. 
@ArkadioG Proszę o uzupełnienie punktu 9.
@krawan13 proszę o dopisanie swojego urządzenia w punkcie 9. do urządzeń testowych
@Sugar1487 proszę o dopisanie swojego urządzenia w punkcie 9 do urządzeń testowych
@de1takrl @pawelbuczynski @KamilGancz konieczne jest uzupełnienie punktu 11.

@ArkadioG @Bllazze @de1takrl @grzegorzgogolewski @jacekfrackiewicz @KamilGancz @KotekMrau @krawan13 @pawelbuczynski @RadoslawBorzyszkowski @Sugar1487 - bardzo Was proszę o uzupełnienie swojej dostępności w punkcie 11., zgodnie z tym, o co prosiłem

@de1takrl Testy systemowe i niefunkcjonalne zostały opisane w punkcie dot. scenariuszy testowych, wydzielę to do osobnego punktu.  Wymagania dopiszę także w osobnym punkcie.

**Comment by ghost** [comment]
@luke-tester Dzięki, dobra robota. Ale teraz odpowiadasz jeszcze za raporty testów poza waflem. Może przygarnąłbyś @Bllazze do testów manualnych? @luke-tester @Bllazze @Sugar1487  @krawan13 chciałbym od każdego z Was raport według wzoru po każdym zakończonym sprincie - wedle Waszych zakresów (mobilka, web czy obie).

[szablonRaportTestowMan.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c8d17f41ca510011ac91e2/125516c66e82c728ace21e0d46fb8e9b218e8ca7bde8af4cb649c4913a5228640405ad693cc7f33ab0487e021b4d44be44510c16fbfddc22f0e03f788c5d0bedd3685d70923911f9aa9e0dfd50e474d412dcfce9c85ecafa3c22ed8a8a4f391905118ef65d37a79a5985.xlsx)

**Comment by luke-tester** [comment]
@de1takrl tak, raport testow bedzie zrobiony po kazdym sprincie. czy w takiej dokladnie formie, czy w nieco innej, przemysle jak podpiac pod to scenariusze Gherkinowe i dam znac ekipie testerow. Bede bazowal na zamieszczonym dokumencie.

**Comment by ghost** [comment]
@luke-tester Fajnie, thx. Aktywizacja zespołu!
