### ISSUE TITLE
Uaktualnienie zakresu projektu

### ISSUE THREAD

**Issue by ghost** [ZespolNumerJeden/zn1#19]
Poprawa błędów odnośnie wykluczeń i kryteriów akceptacji

**Comment by ghost** [comment]
https://docs.google.com/document/d/1lKvcRlgHqLgBQ5BQNFCtgsuEUv3KXMRb-kuhutUBO_Y/edit

**Comment by luke-tester** [comment]
Nie ma zastrzeżeń.
