### ISSUE TITLE
Raport z testów Sprint 2

### ISSUE THREAD

**Issue by luke-tester** [ZespolNumerJeden/zn1#25]
Proszę o uzupełnianie raportu z tesßów dla Waszych zadań. Plan testów zostanie zaktualizowany o numerację scenariuszy, będziecie wiedzieli jak je podpinać pod raport zgodnie z wytycznymi Ryszarda.

**Comment by luke-tester** [comment]
https://drive.google.com/drive/folders/0B243lpRppOQ3UHlud01hUHZCb2c

**Comment by krawan13** [comment]
podpiąłem raport na dysk google
