### ISSUE TITLE
Zaprojektowanie kolorystyki strony i apki

### ISSUE THREAD

**Issue by jacekfrackiewicz** [ZespolNumerJeden/zn1#27]

**Comment by RadoslawBorzyszkowski** [comment]
Załączam dokument z kolorystyką i fontem

[kolorystyka.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e6764d04582b0011d34950/125516c66e82c728ace21e0d46e39b962c909aba9bf0b442e611b2843b492d762a10e17132d0ba2bbd152f04560918af495e5e44fcfb8c29a2e23870df4e17ff933c0120996048e6edc00db513b820814e80b6b48d44c2ee3e24e0898c5d73.pdf)

**Comment by ghost** [comment]
gumijagody
bardzo git
