### ISSUE TITLE
Nowe logo konferencji

### ISSUE THREAD

**Issue by RadoslawBorzyszkowski** [ZespolNumerJeden/zn1#28]
Uniwersalne logo konferencji

**Comment by RadoslawBorzyszkowski** [comment]
Propozycja logo z kaskiem footbolowym

**Comment by RadoslawBorzyszkowski** [comment]
![rect4144.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e6764d04582b0011d34950/125516c66e82c728ace21e0d46fa919937d6d2fddbabf301b44fff9e2c4533317346f6727387b47cba1b7d075c5748ad41585d41fefddd2fa6e32e6c981e5ab38532022d8c6853beb2901eb80bbb258b4782bebf8f48c9e03a20f5c6.png)
![rect2987-1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e6764d04582b0011d34950/125516c66e82c728ace21e0d46fa919937d0daf1d8a4ee01e81fe086264c22703d46f96925dce02ae8167e5809094da447595f44fefc8b2ff2b23c25984019af80330b2b9b645bf9fa9015ad00bd2a8a4a85bebb824fc5ec3422e6899d02.png)
![rect2987-1-2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e6764d04582b0011d34950/125516c66e82c728ace21e0d46fa919937d0daf1d8a4ee0ef61fbcd6395428792c07b7692ac7b671bc402c550a5618fa42505945fcf98b2ea4b268748a0919f1c32f0e2a92624cf5f2d75dad0ba821834584b3bc824bc8eb3821ee8c864e2c53.png)

**Comment by ghost** [comment]
bullseye

**Comment by RadoslawBorzyszkowski** [comment]
jutro wrzucę poprawioną wersję

**Comment by RadoslawBorzyszkowski** [comment]
![v22.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e6764d04582b0011d34950/125516c66e82c728ace21e0d46fec6c861cec1b99de6b546a749b2ce6b137e702b53f72e2983e57be7142a515f5d4bae450c5b44a9eb9539e4e76224d50152a7842f4d7ed43f12a6b9871fb708bf208b4a86b2bc8f5e8d.png)
poprawiony kolor kasku na szary i dodane gradienty do strzałek

**Comment by RadoslawBorzyszkowski** [comment]
@pawelbuczynski  - może zrezygnujmy z koncepcji kasku na rzecz czegoś innego?

**Comment by RadoslawBorzyszkowski** [comment]
![g33.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e6764d04582b0011d34950/125516c66e82c728ace21e0d46efc7c961cec1b99de6b546a749b2ce6b137e702b53f72e2983e57be7142a515f5d4bae450c5b44a9eb9539e4e76224d50152a7842f4d7ed43c16a6b9871fb708bf208f4886b3b9895e8d.png)
tu koncepcja nawiązująca do 3 edycji ogarnij agile - trzy ludziki, w edycji drugiej były dwa to by nawiązywało do części.

**Comment by pawelbuczynski** [comment]
@RadoslawBorzyszkowski tak jak rozmawialiśmy wcześniej aby logo w systemie rejestracji było uniwersalne to KASK, by nie trzeba było zmieniać ludzików. Od razu tak jak powiedziałem Tobie co będzie na 10 edycji konferencji -> 10 ludzików :)

Podsumowując, tworzymy system rejestracji na konferencję i byłbym za tym aby został uniwersalny kask. Jednakże mając już gotowe 3 ludziki też możemy z nich skorzystać. 
Zobaczymy jak to będzie wyglądało finalnie i zdecydujemy wspólnie na zajęciach.

**Comment by luke-tester** [comment]
@pawelbuczynski dobrze byloby ustalic ostateczna wersje nieco wczesniej, aby @RadoslawBorzyszkowski mogl dostarczyc mi nowy splashscreen i ikonke aplikacji => zamknięcie tematu wygladu apki mobilnej ;)

**Comment by ghost** [comment]
Właśnie, 20 ludzików to już niescrumowo. Dodatkowo, te ludziki są bardzo generyczne, nawet jest podobny obrazek z public domain a z kaskiem to i fajny pomysł, i wykonanie.

**Comment by pawelbuczynski** [comment]
Kask jest fajny i niech zostanie :)

**Comment by RadoslawBorzyszkowski** [comment]
przenoszę więc do wykonanych, w osobnym tasku są różne formatki nowego logo
