### ISSUE TITLE
Raport z testów Sprint 3

### ISSUE THREAD

**Issue by ghost** [ZespolNumerJeden/zn1#29]

**Comment by ghost** [comment]
Raport ma dotyczyć obu aplikacji (w tym webowej - produkcyjnej). Raport robicie bezpośrednio po zakończeniu Sprintu i macie się odnosić do wszystkich scenariuszy (w tym niewykonalnych).

**Comment by krawan13** [comment]
raporty testów obu aplikacji umieszczone na dysku https://drive.google.com/drive/folders/0B243lpRppOQ3UHlud01hUHZCb2c

**Comment by luke-tester** [comment]
@Sugar1487 Proszę o uzupełnienie raportów a sprint 3
