### ISSUE TITLE
Raport z testów Sprint 4

### ISSUE THREAD

**Issue by ghost** [ZespolNumerJeden/zn1#30]

**Comment by krawan13** [comment]
Raporty umieszczone na dysku google.

[raport ŁK.1.4 mobile.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59d87b61cab1b50012ab1e4f/125516c66e82c728ace21e0d46fa958a2c9097e92a08940df513a4d42449257a2501e1673295f127b54778154d555ca9480b0d43f8ac807df0b534768b5c0befd46f5b20c23d44bea4905dee5fee7fd616cfe3fe9846d2e9342fe68e8e4d3f1e0c1e80ff5435a98b06.xlsx)
[raport ŁK.1.4 web.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59d87b61cab1b50012ab1e4f/125516c66e82c728ace21e0d46fa958a2c9097e92a08940df513a4d43e4325316546b3397f8fe62bab0021435a561dfe465c0a4daaaf8a23a0b73c70885909e985695f21d42103eee9dc4be05ce36ade0d97bcae8b45cae93824e58a8f463817041c88fb4f78.xlsx)
