### ISSUE TITLE
Scorecardy

### ISSUE THREAD

**Issue by ghost** [ZespolNumerJeden/zn1#31]
Zaliczające zaangażowanych (od minimalnie po bardzo) członków na piątki a niezaangażowanych i wyrzuconych na trójki. Ku pamięci.

**Comment by ghost** [comment]
(Update z rewizją na piątek 01.12,  kończymy ostatni sprint przed zamknięciem produkcji)
Kolejność jak na Slacku.
- Łukasz O. 17 + 4 -> 20
- Arkadiusz 15 +4 -> 19
- Roman 12 +2 -> 14
- Mateusz  12,(9) (work in progress, L4)
- Radosław 12 +2 -> 14
- Łukasz K. 15 (L4)
- Paweł 13 +4 -> 17
- Kamil 7 +2 -> 9 (to do: EA)
- Grzegorz 12,(9) +4 -> 17 (work in progress)
- Jacek 15 +4 -> 19 (work in progress)
- Marcin 9 +2 -> 11 (work in progress)
- Błażej 0 
- Ryszard 16 +3 -> 19 (work in progress)

**Comment by de1takrl** [comment]
Mateusz - duże zaległości. Kamil - zaległości.
