### ISSUE TITLE
Design strony logowania

### ISSUE THREAD

**Issue by ghost** [ZespolNumerJeden/zn1#5]

**Comment by ghost** [comment]
komentarz

**Comment by ghost** [comment]
zaakceptowane

**Comment by jacekfrackiewicz** [comment]
![AgileIT-Mobile.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59d87c68cab1b50012ab1e55/125516c66e82c728ace21e0d46c993932f87aa9dc2c4b041ad51f5d665043761260ea62864c7b96aea1b7803585b1ba5170e5c4cfaf8892ba4b33e74de580bb8c3714d36976345f3e5db55ea43a82a994e82bcbd8f4cc7eb3b25e283864c3c1e1755.png)
