### ISSUE TITLE
Use Cases Diagram Web App

### ISSUE THREAD

**Issue by pawelbuczynski** [ZespolNumerJeden/zn1#8]

**Comment by ghost** [comment]
Web App
![Web App Use Cases.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c8d17f41ca510011ac91e2/125516c66e82c728ace21e0d46df919863a393b9cfdcac46e47ef1872c55653f6b14b1247a80e03cfd183954560c1cab450d5612aafa812da7b63c728f5e0fb9d56d0a66da2f53fde6d640e258f075c95d8fa4bd8246c1ed3d2de78e8a4e381e051889ed10.png)

**Comment by ghost** [comment]
Korekty i synchronzacja na następnych sprintach.

**Comment by ghost** [comment]
![webApp.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c8d17f41ca510011ac91e2/125516c66e82c728ace21e0d46ff9198029293ebc3abaf51ab57f5973d047d317c5da02927d1e671b9442859595e4eac435d5d40a8fd897eb4aa2e32db025fb28c341521842f1bbeba8215be04ba298d4e8dbfb58944c0ee2f68.png)

**Comment by ghost** [comment]
Do korekty - agendę z pliku wprowadza admin-organizator.
